
#
# This LookML file was generated by AtScale on 2025-09-17T16:31:38.073970665Z
#
# AtScale engine version: 2025.5.0.13369
# AtScale DesignCenter version: 2025.5.0.21433
# AtScale version: 2025.5.0.7591
# Organization: default
# Project: Sales Insights

connection: "Looker"
label: "Sales Insights"


include: "/views/Sales_Insights/Internet_Sales_Cube.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

